### ISSUE TITLE
Make cherries functionality

### ISSUE THREAD

**Issue by aniban** [mathananya/pacman#14]
- [x] #15

- [x] when ghosts go over cherries, nothing happens

- [x] when pacman goes over cherry, cherry disappears, and pacman status changes to hungry (self.hungry = True) for next 100 steps

- [x] while pacman is hungry, any collision with ghost kills ghost (ghost dies and goes home)

- [x] if pacman collides with ghost when no hungry - pacman dies - game ends

- [x] pacman can be given a special colour to indicate hungry (while countdown of 100 steps is on)

- [x] #16

- [x] speed during scatter mode should have some slowing so that pacman can hope to catch them

**Comment by mathananya** [comment]
- [x] Bring enemy to life after 100 countdown

**Comment by mathananya** [comment]
> * [x]  pacman can be given a special colour to indicate hungry (while countdown of 100 steps is on)

Pacman will not be given a special colour, enemies will have scared costume instead. Any further changes can be decided later.

**Comment by mathananya** [comment]
Resolved in pull request
